# Generated by Django 4.2.4 on 2023-09-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipodeocorrencia', models.CharField(choices=[('ROUBO', 'Roubo'), ('FURTO', 'Furto'), ('HOMICIDE', 'Homicidio')], max_length=10)),
                ('oc_date', models.DateField(auto_now_add=True)),
                ('descricaoOcorrencia', models.CharField(max_length=500)),
                ('pessoa', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='police_app.pessoa')),
            ],
        ),
    ]
